apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.appName }}
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: port80
      nodePort: 32595
      port: 80
      protocol: TCP
      targetPort: 80
    - name: port443
      nodePort: 30590
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: {{ .Values.global.appName }}
  sessionAffinity: None
  type: NodePort