# alertapi/Chart.yaml
apiVersion: v2
name: alertapi
description: xHCP Test Alert API mikroservisi i√ßin Helm Chart
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - xHCP
  - test
  - alertapi
  - microservice