apiVersion: v2
name: reconciliationapi
description: xHCP Reconciliation API mikroservisi i√ßin Helm Chart
type: application
version: 0.1.0 
appVersion: "1.0.0" 
keywords:
  - xHCP
  - tradesoft
  - reconciliation