apiVersion: v2
name: pricedatareceiver
description: xHCP Price Data Receiver mikroservisi i√ßin Helm Chart
type: application
version: 0.1.0 
appVersion: "1.0.0" 
keywords:
  - xHCP
  - tradesoft
  - pricedata