apiVersion: v2
name: datalicenceapi
description: xHCP DataLicence API mikroservisi i√ßin Helm Chart
type: application
version: 0.1.0 
appVersion: "1.0.0" 
keywords:
  - xHCP
  - fiba
  - datalicenceapi
  - microservice