apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  generation: 1
  name: {{ .Values.global.appName }}-ingress
  namespace: {{ .Values.global.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.global.appName }}
                port:
                  number: 80
            path: /datalicence(/|$)(.*) 
            pathType: ImplementationSpecific