global:
  namespace: xhcp
  appName: tradesoft-xhcp-messaging
  appPrefix: tradesoft-xhcp
  commonSuffix: common

replicaCount: 1 

image:
  repository: io.tradesoft.com.tr/xhcp/messaging 
  tag: dev 
  pullPolicy: Always

config:
  env: "test"
  configMapKeyRefName: xhcp-config-test 
  
  # ----------------------------------------------------
  # ConfigMap İçindeki Değişkenler (Vault/Ortam Bağımlı)
  # ----------------------------------------------------
  
  logging:
    elk:
      enabled: true
      host: elasticsearch 
      username: elastic
      password: "<path:xhcp-test/data/values/#loggingElkPassword>"
      
  kafka:
    securityEnabled: false 
    secure:
      bootstrapservers: "<path:xhcp-test/data/values/#configKafkaSecureBootstrapservers>"
      saslpassword: "<path:xhcp-test/data/values/#configKafkaSecureSaslpassword>" 
      saslusername: "<path:xhcp-test/data/values/#configKafkaSecureSaslusername>"
    insecure: 
      bootstrapservers: "<path:xhcp-test/data/values/#configKafkaInsecureBootstrapservers>"

  redis:
    host: haproxy
    port: 6379
    password: "<path:xhcp-test/data/values/#redisPassword>"

  messagingService:
    sms:
      provider: "GTP"
      enable: false
    email:
      provider: "GTP"
      enable: false
    notification:
      provider: "FIREBASE"
      enable: false

  postaGuvercini:
    endpoint: "https://otpsms.postaguvercini.com/api_ws/smsservice.asmx"
    username: ""
    password: "<path:xhcp-test/data/values/#postaGuverciniPassword>"

  smartMessage:
    baseAddress: "https://api.smartmessage.com"
    tokenPath: "identityapi/openId/user/authenticate"
    smsPath: "otpmanager/transactional/sms/send"
    email: ""
    password: "<path:xhcp-test/data/values/#smartMessagePassword>"
    clientId: ""
    clientSecret: ""
    transactionId: ""
    operator: ""

  dengage:
    baseAddress: "http://10.184.194.11:9050"
    tokenPath: "auth/login"
    smsPath: "transactional/sendSms"
    username: ""
    password: "<path:xhcp-test/data/values/#dengagePassword>"
    accountId: 8
    smsTrustDay: 0
    smsType: "BULK"
    poolId: 57
    preventDuplicate: true
    timeout: 10
    
resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 20m
    memory: 128Mi 

ingress:
  enabled: false