apiVersion: v2
name: cashapi # Chart adı (cashapi)
description: xHCP Cashapi API mikroservisi için Helm Chart
type: application
version: 0.1.0 
appVersion: "1.0.0" 
keywords:
  - xHCP
  - test
  - cashapi
  - microservice