apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.appName }}
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - name: port{{ .Values.service.port }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.global.appName }}
  sessionAffinity: None
  type: ClusterIP