# alertservice/Chart.yaml
apiVersion: v2
name: alertservice # Chart adı
description: xHCP Test Alert Service mikroservisi için Helm Chart
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - xHCP
  - test
  - alertservice
  - microservice