# alertservice/Chart.yaml
apiVersion: v2
name: alertservice
description: xHCP Test Alert Service mikroservisi i√ßin Helm Chart
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - xHCP
  - test
  - alertservice
  - microservice