apiVersion: v2
name: commonapi
description: xHCP Commonapi API mikroservisi i√ßin Helm Chart
type: application
version: 0.1.0 
appVersion: "1.0.0" 
keywords:
  - xHCP
  - test
  - commonapi
  - microservice