apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.appName }}
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - name: port5000
    port: 5000
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.global.appName }}
  sessionAffinity: None
  type: ClusterIP