apiVersion: v2
name: createaccountapi
description: xHCP CreateAccount API mikroservisi i√ßin Helm Chart
type: application
version: 0.1.0 
appVersion: "1.0.0" 
keywords:
  - xHCP
  - test
  - createaccountapi
  - microservice