apiVersion: v2
name: tradewsapi
description: xHCP Trade WebSocket API mikroservisi i√ßin Helm Chart
type: application
version: 0.1.0 
appVersion: "1.0.0" 
keywords:
  - xHCP
  - tradesoft
  - websocket