apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.appName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appName }}
spec:
  # values.yaml'dan gelen replika sayÄ±sÄ±
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.global.appName }}
  template:
    metadata:
      # MatchLabels ile aynÄ± etiketi kullanÄ±r
      labels:
        app: {{ .Values.global.appName }}
    spec:
      # Image Pull Secret (Nexus)
      imagePullSecrets:
        - name: nexus2
      containers:
        - name: {{ .Values.global.appName }}
          # Image ve Tag deÄŸerleri
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          
          # ðŸš¨ TÃœM ENV DEÄžÄ°ÅžKENLERÄ° ConfigMap'ten Ã‡ekiliyor ðŸš¨
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: RbApiClient__URL
              valueFrom:
                configMapKeyRef:
                  key: RbApiClient__URL
                  name: {{ include "alertservice.envConfigMapRefName" . }}
            - name: Logging__ELK__Enabled
              valueFrom:
                configMapKeyRef:
                  key: Logging__ELK__Enabled
                  name: {{ include "alertservice.envConfigMapRefName" . }}
            - name: Logging__ELK__Url
              valueFrom:
                configMapKeyRef:
                  key: Logging__ELK__Url
                  name: {{ include "alertservice.envConfigMapRefName" . }}
            - name: Logging__ELK__Username
              valueFrom:
                configMapKeyRef:
                  key: Logging__ELK__Username
                  name: {{ include "alertservice.envConfigMapRefName" . }}
            - name: Logging__ELK__Password
              valueFrom:
                configMapKeyRef:
                  key: Logging__ELK__Password
                  name: {{ include "alertservice.envConfigMapRefName" . }}
            - name: Company
              valueFrom:
                configMapKeyRef:
                  key: Company
                  name: {{ include "alertservice.envConfigMapRefName" . }}
            - name: DataSourceConfig__Source
              valueFrom:
                configMapKeyRef:
                  key: DataSourceConfig__Source
                  name: {{ include "alertservice.envConfigMapRefName" . }}
            - name: IdentityServer__Uri
              valueFrom:
                configMapKeyRef:
                  key: IdentityServer__Uri
                  name: {{ include "alertservice.envConfigMapRefName" . }}
            - name: PDApiClientSettings__URL
              valueFrom:
                configMapKeyRef:
                  key: PDApiClientSettings__URL
                  name: {{ include "alertservice.envConfigMapRefName" . }}
            - name: Redis__Host
              valueFrom:
                configMapKeyRef:
                  key: Redis__Host
                  name: {{ include "alertservice.envConfigMapRefName" . }}
            - name: Redis__Port
              valueFrom:
                configMapKeyRef:
                  key: Redis__Port
                  name: {{ include "alertservice.envConfigMapRefName" . }}
            - name: Redis__Password
              valueFrom:
                configMapKeyRef:
                  key: Redis__Password
                  name: {{ include "alertservice.envConfigMapRefName" . }}
            - name: Redis__DbId
              valueFrom:
                configMapKeyRef:
                  key: Redis__DbId
                  name: {{ include "alertservice.envConfigMapRefName" . }}
            - name: Redis__Configuration
              valueFrom:
                configMapKeyRef:
                  key: Redis__Configuration
                  name: {{ include "alertservice.envConfigMapRefName" . }}
            - name: KafkaProducer__bootstrapservers
              valueFrom:
                configMapKeyRef:
                  key: KafkaProducer__bootstrapservers
                  name: {{ include "alertservice.envConfigMapRefName" . }}
            - name: KafkaConsumer__bootstrapservers
              valueFrom:
                configMapKeyRef:
                  key: KafkaConsumer__bootstrapservers
                  name: {{ include "alertservice.envConfigMapRefName" . }}
            - name: MssqlDbConfig__ConnectionString
              valueFrom:
                configMapKeyRef:
                  key: MssqlDbConfig__ConnectionString
                  name: {{ include "alertservice.envConfigMapRefName" . }}
            - name: AltibaseDbConfig__ConnectionString
              valueFrom:
                configMapKeyRef:
                  key: AltibaseDbConfig__ConnectionString
                  name: {{ include "alertservice.envConfigMapRefName" . }}
            - name: ReportApiSettings
              valueFrom:
                configMapKeyRef:
                  key: ReportApiSettings
                  name: {{ include "alertservice.envConfigMapRefName" . }}
            - name: ReportApiSettings__URL
              valueFrom:
                configMapKeyRef:
                  key: ReportApiSettings__URL
                  name: {{ include "alertservice.envConfigMapRefName" . }}
            - name: ConnectionStrings__DbContext
              valueFrom:
                configMapKeyRef:
                  key: ConnectionStrings__DbContext
                  name: {{ include "alertservice.envConfigMapRefName" . }}
            - name: DataSource
              valueFrom:
                configMapKeyRef:
                  key: DataSource
                  name: {{ include "alertservice.envConfigMapRefName" . }}

          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443 # Ä°kinci Port Eklendi
              protocol: TCP
          
          # Kaynak (Resource) Limitleri ve Ä°stekleri
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          
          # ConfigMap'i mount etme
          volumeMounts:
            - mountPath: /app/appsettings.json
              name: config-vol
              readOnly: true
              # Dinamik subPath adÄ±
              subPath: {{ .Values.global.appPrefix }}-alertservice-appsettings.k8s.json
              
      terminationGracePeriodSeconds: 30
      # ConfigMap'i Volume olarak tanÄ±mlama
      volumes:
        - configMap:
            defaultMode: 420
            # helpers.tpl'den gelen dinamik ConfigMap adÄ±
            name: {{ include "alertservice.envConfigMapRefName" . }}
          name: config-vol
